export * from "./$_id";
export * from "./$Assessment";
export * from "./$Pagination";
export * from "./$Section";
export * from "./$StudentRecord";
export * from "./$StudentVerification";
export * from "./$Tuition";
export * from "./$Filter";
export * from "./$Grade";
